[tool.poetry]
name = "agpt-turbo"
version = "0.4.7"
authors = [
  "Significant Gravitas <support@agpt.co>",
  "lc0rp"
]
readme = "README.md"
description = "An Experimental Auto-GPT fork"
homepage = "https://github.com/lc0rp/Auto-GPT-Turbo"
#requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
packages = [{ include = "autogpt" }]

[tool.poetry.scripts]
autogpt = "autogpt.app.cli:main"

[tool.poetry.dependencies]
python = "^3.10"
agent-protocol = "*"
beautifulsoup4 = "^4.12.2"
charset-normalizer = "^3.1.0"
click = "*"
colorama = "^0.4.6"
distro = "^1.8.0"
docker = "*"
duckduckgo-search = "^3.0.2"
en-core-web-sm = {url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.5.0/en_core_web_sm-3.5.0-py3-none-any.whl"}
ftfy = "^6.1.1"
google-api-python-client = "*"
gTTS = "^2.3.1"
inflection = "*"
jsonschema = "*"
markdown = "*"
openai = "*"
orjson = "^3.8.10"
Pillow = "*"
playsound = "~1.2.2"
prompt_toolkit = "^3.0.38"
pydantic = "*"
pylatexenc = "*"
PyPDF2 = "*"
pytimedinput = "*"
python-docx = "*"
python-dotenv = "^1.0.0"
pyyaml = "^6.0"
readability-lxml = "^0.8.1"
requests = "*"
sarge = "*"
scalene = "*"
selenium = "^4.11.2"
spacy = "^3.0.0"
tiktoken = "*"
webdriver-manager = "*"
yappi = "*"

# web server
fastapi = "*"
uvicorn = "*"

# OpenAI and Generic plugins import
openapi-python-client = "*"

[tool.poetry.group.dev.dependencies]
auto-gpt-plugin-template = {git = "https://github.com/Significant-Gravitas/Auto-GPT-Plugin-Template", rev = "0.1.0"}
black = "*"
coverage = "*"
flake8 = "*"
gitpython = "^3.1.32"
isort = "*"
mypy = "*"
numpy = "*"
pre-commit = "*"
types-beautifulsoup4 = "*"
types-colorama = "*"
types-Markdown = "*"
types-Pillow = "*"

# Testing dependencies
asynctest = "*"
pytest = "*"
pytest-asyncio = "*"
pytest-benchmark = "*"
pytest-cov = "*"
pytest-integration = "*"
pytest-mock = "*"
pytest-recording = "*"
pytest-xdist = "*"
vcrpy = {git = "https://github.com/Significant-Gravitas/vcrpy.git", rev = "master"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'
packages = ["autogpt"]
extend-exclude = '.+/(dist|.venv|venv|build)/.+'


[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
sections = [
    "FUTURE",
    "STDLIB",
    "THIRDPARTY",
    "FIRSTPARTY",
    "LOCALFOLDER"
]
skip = '''
    .tox
    __pycache__
    *.pyc
    .env
    venv*/*
    .venv/*
    reports/*
    dist/*

'''

[tool.pytest.ini_options]
markers = [
    "requires_openai_api_key",
    "requires_huggingface_api_key"
]

[tool.ruff]
line-length = 88