# To boot the app run the following:
# docker-compose run auto-gpt
version: '3.9'

services:
  auto-gpt:
    build:
      dockerfile: .devcontainer/Dockerfile
      context: ../
    tty: true
    volumes:
      - ../:/workspace/Auto-GPT
      - ~/Documents/dev/python/Auto-GPT-Plugins:/workspace/Auto-GPT/plugins/Auto-GPT-Plugins
